# Generated by Django 5.1.3 on 2024-12-26 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.userprofile')),
                ('nom_societe', models.CharField(max_length=255)),
                ('logo_societe', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('secteur_activite', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('site_web', models.URLField(blank=True, null=True)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('taille_entreprise', models.CharField(max_length=100)),
                ('annee_creation', models.IntegerField()),
            ],
            bases=('core.userprofile',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.userprofile')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('etablissement', models.CharField(max_length=255)),
                ('filiere', models.CharField(max_length=255)),
                ('niveau_etude', models.CharField(max_length=100)),
                ('annee_graduation', models.IntegerField()),
                ('type_recherche', models.CharField(max_length=255)),
                ('date_disponibilite', models.DateField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='student_cv/')),
                ('portfolio', models.URLField(blank=True, null=True)),
            ],
            bases=('core.userprofile',),
        ),
    ]
